# Site settings
# title: PhD Candidate in Finance at Schulich School of Business (York University)
# author:
#  name: Afshin Cheraghi
#  email: cheraghi@schulich.yorku.ca
#description: "This is a page where I indtroduce myself"

# Build settings
 remote_theme: pages-themes/cayman
