# Site settings
 title: PhD Candidate in Finance at Schulich School of Business (York University)
 author: Afshin Cheraghi
  name: Afshin Cheraghi
  email: cheraghi@schulich.yorku.ca
description: "This is a page where I indtroduce myself and my projects"

# Build settings
 theme: cayman
