# Site settings
title: Great New Blog Title
author:
  name: Afshin Cheraghi
  email: cheraghi@schulich.yorku.ca
description: "This is my website where I introduce my projects"

# Build settings
remote_theme: jekyll/minima
